import {Key} from '~/api/types';

const KEYBOARD: Key[] = [
    {row: 1, code: 'Backquote', text:'`'},
    {row: 1, code: 'Digit1', text:'1'},
    {row: 1, code: 'Digit2', text:'2'},
    {row: 1, code: 'Digit3', text:'3'},
    {row: 1, code: 'Digit4', text:'4'},
    {row: 1, code: 'Digit5', text:'5'},
    {row: 1, code: 'Digit6', text:'6'},
    {row: 1, code: 'Digit7', text:'7'},
    {row: 1, code: 'Digit8', text:'8'},
    {row: 1, code: 'Digit9', text:'9'},
    {row: 1, code: 'Digit0', text:'0'},
    {row: 1, code: 'Minus', text:'-'},
    {row: 1, code: 'Equal', text:'='},
    {row: 1, code: 'Delete', text: 'DEL'},
    {row: 2, code:'Tab', utility: true, text: 'Tab'},
    {row: 2, code: 'KeyQ', text: 'Q'},
    {row: 2, code: 'KeyW', text: 'W'},
    {row: 2, code: 'KeyE', text: 'E'},
    {row: 2, code: 'KeyR', text: 'R'},
    {row: 2, code: 'KeyT', text: 'T'},
    {row: 2, code: 'KeyY', text: 'Y'},
    {row: 2, code: 'KeyU', text: 'U'},
    {row: 2, code: 'KeyI', text: 'I'},
    {row: 2, code: 'KeyO', text: 'O'},
    {row: 2, code: 'KeyP', text: 'P'},
    {row: 2, code: 'BracketLeft', text: '['},
    {row: 2, code: 'BracketRight', text: ']'},
    {row: 2, code: 'Backslash', text: '\\'},
    {row: 3, code: 'CapsLock', text: 'CAPS', utility: true},
    {row: 3, code: 'KeyA', text: 'A'},
    {row: 3, code: 'KeyS', text: 'S'},
    {row: 3, code: 'KeyD', text: 'D'},
    {row: 3, code: 'KeyF', text: 'F'},
    {row: 3, code: 'KeyG', text: 'G'},
    {row: 3, code: 'KeyH', text: 'H'},
    {row: 3, code: 'KeyJ', text: 'J'},
    {row: 3, code: 'KeyK', text: 'K'},
    {row: 3, code: 'KeyL', text: 'L'},
    {row: 3, code: 'Semicolon', text: ';'},
    {row: 3, code: "Quote", text: "'"},
    {row: 3, code: 'Enter', text: 'ENTER', utility: true},
    {row: 4, code: 'ShiftLeft', text:'SHIFT', utility: true},
    {row: 4, code: 'KeyZ', text: 'Z'},
    {row: 4, code: 'KeyX', text: 'X'},
    {row: 4, code: 'KeyC', text: 'C'},
    {row: 4, code: 'KeyV', text: 'V'},
    {row: 4, code: 'KeyB', text: 'B'},
    {row: 4, code: 'KeyN', text: 'N'},
    {row: 4, code: 'KeyM', text: 'M'},
    {row: 4, code: 'Comma', text: ','},
    {row: 4, code: 'Period', text: '.'},
    {row: 4, code: 'Slash', text: '/'},
    {row: 4, code: 'ShiftRight', text: 'SHIFT', utility: true}
];

export {KEYBOARD};
